services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -d db_prod
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432


  app:
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:8000
      interval: 10s
      timeout: 3s
      retries: 3
    build:
      context: .
    ports:
    - 8000:8000
    volumes:
    - ./.docker/app.cfg:/app/app.cfg

volumes:
    db_data: