services:
  postgres:
    image: postgres:16
    env_file:
      - ./.docker/.env
    healthcheck:
      test: pg_isready -d db_prod
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./.docker/data:/data
    ports:
      - 5432:5432

  localstack:
    image: localstack/localstack:3.2
    environment:
    - SERVICES=sns
    - AWS_DEFAULT_REGION=eu-east-1

  app:
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:8000
      interval: 10s
      timeout: 3s
      retries: 3
    build:
      context: .
    ports:
    - 8000:8000
    volumes:
    - ./install.sh:/app/install.sh

volumes:
    db_data: