# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=255)),
                ('msid', models.PositiveIntegerField(help_text='article identifier from beginning of submission process right through to end of publication.', unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('doi', models.CharField(max_length=255)),
                ('impact_statement', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Correction', 'correction'), ('Editorial', 'editorial'), ('Feature', 'feature'), ('Insight', 'insight'), ('Research Advance', 'research-advance'), ('Research Article', 'research-article'), ('Research Exchange', 'research-exchange'), ('Retraction', 'retraction'), ('Registered Report', 'registered-report'), ('Replication Study', 'replication-study'), ('Short Report', 'short-report'), ('Tools Resources', 'tools-resources'), ('Unknown Type', 'unknown-type')], help_text='article as exported from EJP submission system', max_length=50)),
                ('current_version', models.PositiveSmallIntegerField(null=True)),
                ('status', models.CharField(choices=[('poa', 'POA'), ('vor', 'VOR')], max_length=3, null=True)),
                ('volume', models.PositiveSmallIntegerField(null=True)),
                ('num_authors', models.PositiveSmallIntegerField(null=True)),
                ('num_references', models.PositiveSmallIntegerField(null=True)),
                ('num_poa_versions', models.PositiveSmallIntegerField(default=0)),
                ('num_vor_versions', models.PositiveSmallIntegerField(default=0)),
                ('datetime_submitted', models.DateTimeField(help_text='when the author uploaded their article', null=True)),
                ('num_revisions', models.PositiveSmallIntegerField(help_text='number of revisions article has currently gone through', null=True)),
                ('datetime_initial_qc_complete', models.DateTimeField(help_text='when author hands off submission for review', null=True)),
                ('datetime_initial_decision', models.DateTimeField(help_text='when decision to accept/reject/revise was made', null=True)),
                ('initial_decision', models.CharField(choices=[('reject-initial-submission', 'RJI'), ('reject-full-submission', 'RJF'), ('revise-full-submission', 'RVF'), ('accept-full-submission', 'AF'), ('encourage-full-submission', 'EF'), ('simple-withdraw', 'SW')], max_length=25, null=True)),
                ('datetime_full_qc', models.DateField(null=True)),
                ('datetime_full_decision', models.DateField(null=True)),
                ('decision', models.CharField(choices=[('reject-initial-submission', 'RJI'), ('reject-full-submission', 'RJF'), ('revise-full-submission', 'RVF'), ('accept-full-submission', 'AF'), ('encourage-full-submission', 'EF'), ('simple-withdraw', 'SW')], max_length=25, null=True)),
                ('datetime_accept_decision', models.DateTimeField(help_text='this is a accept OR reject decision', null=True)),
                ('accepted_in_revision', models.PositiveSmallIntegerField(help_text='in which revision was the manuscript accepted?', null=True)),
                ('datetime_entered_review', models.DateTimeField(null=True)),
                ('datetime_entered_production', models.DateTimeField(null=True)),
                ('datetime_published', models.DateTimeField(null=True)),
                ('datetime_version_published', models.DateTimeField(help_text='date and time current version of article published')),
                ('datetime_poa_published', models.DateTimeField(help_text='date and time first POA version published', null=True)),
                ('datetime_vor_published', models.DateTimeField(help_text='date and time first VOR version published', null=True)),
                ('days_submission_to_acceptance', models.PositiveSmallIntegerField(null=True)),
                ('days_submission_to_review', models.PositiveSmallIntegerField(null=True)),
                ('days_submission_to_production', models.PositiveSmallIntegerField(null=True)),
                ('days_submission_to_publication', models.PositiveSmallIntegerField(null=True)),
                ('days_accepted_to_review', models.PositiveSmallIntegerField(null=True)),
                ('days_accepted_to_production', models.PositiveSmallIntegerField(null=True)),
                ('days_accepted_to_publication', models.PositiveSmallIntegerField(null=True)),
                ('days_review_to_production', models.PositiveSmallIntegerField(null=True)),
                ('days_review_to_publication', models.PositiveSmallIntegerField(null=True)),
                ('days_production_to_publication', models.PositiveSmallIntegerField(null=True)),
                ('days_publication_to_current_version', models.PositiveSmallIntegerField(help_text='day elapsed between v1 and current versionb', null=True)),
                ('num_views', models.PositiveIntegerField(default=0)),
                ('num_downloads', models.PositiveIntegerField(default=0)),
                ('num_citations', models.PositiveIntegerField(default=0)),
                ('has_digest', models.NullBooleanField(help_text="Null/None means I don't know!")),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
