# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author_email',
            field=models.EmailField(help_text='corresponding author email.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author_line',
            field=models.TextField(help_text="abbreviated way of referring to the article's authors", null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(help_text='coresponding author name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('poa', 'POA'), ('vor', 'VOR')], help_text="article's current status (poa or vor)", max_length=3, null=True),
        ),
    ]
