# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0004_auto_20170424_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='observer.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='subjects',
            field=models.ManyToManyField(to='observer.Subject'),
        ),
    ]
