# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0005_auto_20170424_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('name',)},
        ),
    ]
