# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0008_auto_20171018_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlejson',
            name='msid',
            field=models.PositiveIntegerField(),
        ),
    ]
