# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0010_auto_20180114_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlejson',
            name='ajson_type',
            field=models.CharField(choices=[('lax-ajson', 'lax article json'), ('elife-metrics-summary', 'elife-metrics summary data')], default='lax-ajson', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlejson',
            name='version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
