# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0014_auto_20180209_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='orcid',
        ),
    ]
