# Generated by Django 2.2.16 on 2020-10-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0015_auto_20180211_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlejson',
            name='ajson_type',
            field=models.CharField(choices=[('lax-ajson', 'lax article json'), ('elife-metrics-summary', 'elife-metrics summary data'), ('press-packages-id', 'presspackage summary data'), ('profiles-id', 'profiles'), ('digests-id', 'digests')], max_length=25),
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('impact_statement', models.TextField()),
                ('image_uri', models.URLField(max_length=500)),
                ('image_height', models.PositiveSmallIntegerField()),
                ('image_width', models.PositiveSmallIntegerField()),
                ('image_mime', models.CharField(choices=[('jpg', 'image/jpeg'), ('png', 'image/png')], max_length=10)),
                ('datetime_published', models.DateTimeField()),
                ('datetime_updated', models.DateTimeField()),
                ('datetime_record_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_record_updated', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(to='observer.Subject')),
            ],
            options={
                'ordering': ('-datetime_published',),
            },
        ),
    ]
