# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0015_auto_20180211_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='datetime_record_created',
            field=models.DateField(default=django.utils.timezone.now, help_text='added to the *observer database*, not date of profile creation'),
        ),
    ]
