# Generated by Django 2.2.16 on 2020-10-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0016_auto_20201012_0505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleJSON',
            new_name='RawJSON',
        ),
    ]
