# Generated by Django 2.2.16 on 2020-10-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0018_auto_20201020_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('interview', 'interview'), ('collection', 'collection'), ('blog-article', 'blog-article'), ('feature', 'feature'), ('digest', 'digest'), ('labs-post', 'labs-post')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('image_uri', models.URLField(max_length=500, null=True)),
                ('image_height', models.PositiveSmallIntegerField(null=True)),
                ('image_width', models.PositiveSmallIntegerField(null=True)),
                ('image_mime', models.CharField(choices=[('jpg', 'image/jpeg'), ('png', 'image/png')], max_length=10, null=True)),
                ('datetime_published', models.DateTimeField()),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_record_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_record_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-datetime_updated', '-datetime_published'),
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='rawjson',
            name='json_type',
            field=models.CharField(choices=[('lax-ajson', 'lax article json'), ('elife-metrics-summary', 'elife-metrics summary data'), ('press-packages-id', 'presspackage summary data'), ('profiles-id', 'profiles'), ('digest', 'digests')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Digest',
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(to='observer.ContentCategory'),
        ),
    ]
