# Generated by Django 2.2.16 on 2020-10-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0018_auto_20201020_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabsPost',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('datetime_published', models.DateTimeField()),
                ('image_uri', models.URLField(max_length=500)),
                ('image_height', models.PositiveSmallIntegerField()),
                ('image_width', models.PositiveSmallIntegerField()),
                ('image_mime', models.CharField(choices=[('jpg', 'image/jpeg'), ('png', 'image/png')], max_length=10)),
                ('impact_statement', models.TextField()),
                ('datetime_record_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_record_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-datetime_published',),
            },
        ),
    ]
