# Generated by Django 2.2.16 on 2020-11-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0019_auto_20201026_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('interview', 'interview'), ('collection', 'collection'), ('blog-article', 'blog-article'), ('feature', 'feature'), ('digest', 'digest'), ('labs-post', 'labs-post'), ('editorial', 'editorial'), ('podcast', 'podcast')], max_length=12),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['type'], name='type_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='content_type_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjson',
            index=models.Index(fields=['msid', 'json_type'], name='msid_json_type_idx'),
        ),
    ]
