# Generated by Django 2.2.20 on 2021-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0020_auto_20201119_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='social_image_height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='social_image_mime',
            field=models.CharField(choices=[('jpg', 'image/jpeg'), ('png', 'image/png')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='social_image_uri',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='social_image_width',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
