# Generated by Django 3.2.13 on 2022-05-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0021_auto_20210413_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='has_digest',
            field=models.BooleanField(blank=True, help_text="Null/None means I don't know!", null=True),
        ),
    ]
