# Generated by Django 3.2.20 on 2023-09-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0023_article_has_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('interview', 'interview'), ('collection', 'collection'), ('blog-article', 'blog-article'), ('feature', 'feature'), ('digest', 'digest'), ('labs-post', 'labs-post'), ('editorial', 'editorial'), ('podcast', 'podcast'), ('reviewed-preprint', 'reviewed-preprint')], max_length=17),
        ),
    ]
